% Define the file path
gfp_filepath = 'export_1_BL150_beads.csv';
%gfp_filepath = 'export_iptginduced-str9_cells gfp+.csv';
%data_nogfp = readmatrix(nogfp_filepath, 'HeaderLines', 1);
data_gfp = readmatrix(gfp_filepath, 'HeaderLines', 1);


[y_gfp,x_gfp] = hist(data_gfp,500);
y_gfp=y_gfp(:,1);

%[y_nogfp,x_nogfp] = hist(data_nogfp,1000);
%y_nogfp=y_nogfp(:,1);

figure
plot(x_gfp,y_gfp);


createFit(x_gfp, y_gfp)


function [fitresult, gof] = createFit(x_gfp, y_gfp)
%CREATEFIT(X_GFP,Y_GFP)
%  Create a fit.
%
%  Data for 'untitled fit 3' fit:
%      X Input: x_gfp
%      Y Output: y_gfp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Oct-2023 11:58:17


%% Fit: 'untitled fit 3'.
[xData, yData] = prepareCurveData( x_gfp, y_gfp );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [275 50522.538 76879.9345394125];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 3' );
h = plot( fitresult, xData, yData, 'predobs' );
legend( h, 'data', 'fitted curve', 'prediction bounds', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'GFP fluorescence (RFI)', 'Interpreter', 'none', 'FontSize', 16);
ylabel( 'Count', 'Interpreter', 'none', 'FontSize', 16);
set(gca, 'FontSize', 14); % Set font size for axis labels and tick labels
set(gcf,'position',[100,100,400,400])
grid off

end

