
filename='FWHMAmplitude_001.tdms';
my_tdms_struct = TDMS_getStruct(filename);

i=1;
for k = 5:20  %set fwhm thresholds
    fwhms{i} = ['Untitled_' num2str(k)];
    i=i+1;
end

combined=[];
for j = 1:length(fwhms)
    combined=[combined; my_tdms_struct.Untitled.(fwhms{j}).data];
end

min_sort=2.9; %set fluorescence sorting thresholds
max_sort=4.2; %set fluorescence sorting thresholds

thr_min=min_sort*200;
thr_max=max_sort*200;
sorted_ev=sum(combined(:,[thr_min:thr_max]));
sorted_ev=sum(sorted_ev(:));


events=sum(combined(:));
eventslabel = sprintf('total events = %d', events);
eventslabel2 = sprintf('sorted events = %d', sorted_ev); 

figure 
set(gcf, 'Position',  [100, 100, 375, 700])
% contour plot
subplot(2,1,1)
x=[1:2000].*0.005;
y=[5:20]*10; %set fwhm thresholds
contour(x,y,combined(:,[1:2000],:),[50]);
%xline(min_sort,'r');
%xline(max_sort,'r');
xlabel('Fluorescence (RFI)')
ylabel('FWHM (μs)')
mycolormap = customcolormap([0 .25 .5 .75 1], {'#9d0142','#f66e45','#ffffbb','#65c0ae','#5e4f9f'});
colorbar('southoutside');
colormap(mycolormap);

%histogram
subplot(2,1,2)
x=[1:2000].*0.005;
plot(x,sum(combined(:,1:2000), 1));
hold on
%xline(min_sort,'r');
%xline(max_sort,'r');
hold on;
%plot(x(locs), peaks, 'ro');  % Mark the identified peaks
xL=xlim;
yL=ylim;
xlabel('Fluorescence (RFI)')
ylabel('Count')
set(gca, 'XScale', 'log')
axis([0.1 10 0 1500])
%text(6.1,0.9*yL(2),eventslabel)
%text(6.1,0.8*yL(2),eventslabel2)

x_values = [1:2000] .* 0.005; 
locs = interp1(x_values, 1:length(x_values), locs, 'nearest');

data = sum(combined(:,1:2000), 1);


createFit(x, data)



function [fitresult, gof] = createFit(x, data)
%CREATEFIT(X,DATA)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input: x
%      Y Output: data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Oct-2023 23:29:32


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( x, data );

% Set up fittype and options.
ft = fittype( 'gauss3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [1094 1.2 0.497705377549117 860 5.115 0.313803411998029 805.999999032859 3.69 0.562139841458691];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData, 'predobs' );
legend( h, 'data', 'fitted curve', 'prediction bounds', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Fluorescence (RFI)', 'Interpreter', 'none' );
ylabel( 'Count', 'Interpreter', 'none' );

end
